version: '3.8'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    container_name: node-libros-api
    environment:
      - MONGO_URI=mongodb://mongo:27017/librosdb
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    container_name: node-libros-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
